version: "3.8"

networks:
  nginx-php-mysql:


services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    networks:
      nginx-php-mysql:
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
        - "8080:80"
    volumes:
        - ./app:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      nginx-php-mysql:




